version: "3.9"

services:
  airflow:
    image: apache/airflow:2.8.3-python3.11
    container_name: wine_airflow
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
      AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"
    user: "50000:50000"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./code:/opt/airflow/code
    entrypoint: >
      bash -c "
        pip install --user --no-cache-dir dvc==3.42.0 &&
        airflow db init &&
        airflow users create --username admin --password admin --firstname Airflow --lastname Admin --role Admin --email admin@example.com &&
        exec airflow standalone
      "
    ports:
      - "8080:8080"

  api:
    build:
      context: ../../
      dockerfile: code/deployment/api/Dockerfile
    container_name: wine_quality_api
    volumes:
      - ../../models:/app/models:ro
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    ports:
      - "8000:8000"

  app:
    build:
      context: ../../
      dockerfile: code/deployment/app/Dockerfile
    container_name: wine_quality_app
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
    restart: unless-stopped
    ports:
      - "8501:8501"
